FROM php:7.3-apache 
RUN docker-php-ext-install mysqli pdo_mysql
RUN apt-get update \
    && apt-get install -y libzip-dev \
    && apt-get install -y zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip  \
    && docker-php-ext-install mcrypt pdo_mysql \
    && pecl install imagick \
    && docker-php-ext-install php-mbstring
